# エラーハンドリング

Go言語では他言語にあるようなtry-catch構文が例外送出の仕組みが存在しない

その為、関数の複数の戻り値を利用したerrorインタフェースの利用をする

    err := f()
    if err != nil {
    	log.Fatal(err)
    }
    
    if err := f(); err != nil {
    	log.Fatal(err)
    }

任意のエラー作成には `errors.New`, または `fmt.Errorf`が利用できる

呼び出し元では関数の戻り値をerrとして受け取り、nil判定してエラー処理を行う方法が一般的

    func f1() error {
      return errors.New("ERROR")
    }
    
    func f2() error {
    	emsg := "エラーメッセージ"
    	return fmt.Errorf("ERROR: %s", emsg)
    }

エラーコードやエラー内容、その他のエラーに関する情報など、

細かく定義しそれを判定したい場合は、独自のエラー構造体を定義する方法もある

（ただしエラーを送出する手間が増えるので、個人的には小さいコード断片ではやらない）

    type Exception struct {
    	Code int
    	Error error
    	Message string
    }
    
    func f() Exception {
    	return Exception{
    		Code: 1,
    		Error: errors.New("Error"),
    		Message: "エラーの詳細",
    	}
    }